### PR TITLE
fix: invalid property field on `appConfig` being accessed

### LINKED ISSUE #21: BUG: Doesn't pull the actual Discord character limit.
Wrong naming convention!
` const charLimit = (process.env.T2D_DISCORD_CHAR_LIMIT ? process.env.T2D_DISCORD_CHAR_LIMIT : appConfig.discord.DISCORD_CHAR_LIMIT) || 4000;`

The actual appConfig property is `discord_char_limit` lowercased (:

### PR DESCRIPTION
**Pull request by AceLikesGhosts**
fixes #21

### CODE REVIEW

**Comment by AceLikesGhosts** [comment]
Once/if this is merged I'm going to follow up with a PR that implements types for the new `appConfig.js` file (: (the export) so that this HOPEFULLY does not happen again :p

**Comment by iSlammedMyKindle** [comment]
That's actually a good catch!

This line in general actually needs to be changed so that it's not directly accessing the environment variables. appConfig should be the only source of truth because it parses the variables in advance

so that `||` statement on the left-hand side should be destroyed.

**Comment by AceLikesGhosts** [comment]
If `appConfig` is the only source we should be checking for it, is it safe to just drop the `charLimit` variable and just directly access `appConfig.discord.discord_char_limit` where ever needed? Or should I keep the aliased variable (:

**Comment by iSlammedMyKindle** [comment]
> Once/if this is merged I'm going to follow up with a PR that implements types for the new `appConfig.js` file (: (the export) so that this HOPEFULLY does not happen again :p
> 
> EDIT: I'd review and merge this myself although I want to make sure that
> 
> 1. You don't mind me doing some random PRs here and there
> 2. That this was not intended

Due to how permissions are setup, it won't be possible to self-approve, I don't intend on changing this.
You're welcome to make changes if you like - it may be tricky to make them without a twitch account however, but you may want to invest looking into how the twitch mock system works; it could help, but it might be involved as I haven't seen any docs on how twurple could use this.

**Comment by iSlammedMyKindle** [comment]
As for the appConfig.js I don't intend on making this typescript, because it was deliberately designed to work with fuzzy variables from the ground up.

You could try your hand at adding types, but I don't think I'll merge a change like that as much as that bites XP

**Comment by AceLikesGhosts** [comment]
😭what about the aliased variable

**Comment by iSlammedMyKindle** [comment]
image
I think you're pretty close - but the restriction I'm seeing from this item is that the person needs write access to the repo

**Comment by AceLikesGhosts** [comment]
Ahh! I was looking at the `merging is blocked` part at the bottom! 
image

Anywho, comments on just removing the `charLimit` alias variable?

**Comment by iSlammedMyKindle** [comment]
Yeah, I changed those a long time ago, but I can check again

Regarding the charLimit var - for now I'd keep it; it would be more ideal if I implemented a "default" variable in appConfig, but I didn't.

The original reason I think this was here in the first place was to limit the size of outgoing twitch messages. I don't think everyone wants a bot spamming multiple messages at once, so it's a software limit imposed for the safety of the streamer

**Comment by AceLikesGhosts** [comment]
OOP. I PUSHED THAT COMMIT BEFORE I SAW THE COMMENT

**Comment by iSlammedMyKindle** [comment]
all good XP

**Comment by iSlammedMyKindle** [comment]
Looks good!

**Review by iSlammedMyKindle — APPROVED** [review]

**Comment by AceLikesGhosts** [comment]
Wait a second before merging, I wanna see if it will let me approve my own PR

**Review by AceLikesGhosts — COMMENTED** [review]
😭

**Comment by iSlammedMyKindle** [comment]
oops @_@

**Comment by AceLikesGhosts** [comment]
OK, good; cant actually (:

**Comment by AceLikesGhosts** [comment]
we good we good

**Comment by iSlammedMyKindle** [comment]
Thank you for the PR!

**Pull request merged**
